[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=optional && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
